In [1]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv("./cleaned_data.csv", parse_dates=['started_at', 'ended_at'])
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:00,2020-04-26 18:12:00,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:00,2020-04-17 17:17:00,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:00,2020-04-01 18:08:00,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:00,2020-04-07 13:02:00,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:00,2020-04-18 11:15:00,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual

In [30]:
# Checking conversion
data_types = df.dtypes

# Display the result
print(data_types)

ride_id                       object
rideable_type                 object
started_at            datetime64[ns]
ended_at              datetime64[ns]
start_station_name            object
start_station_id               int64
end_station_name              object
end_station_id               float64
start_lat                    float64
start_lng                    float64
end_lat                      float64
end_lng                      float64
member_casual                 object
dtype: object

In [31]:
# Calculate the mean of 'numeric_column'
df['ride_duration'] = (df['ended_at'] - df['started_at']).dt.total_seconds() / 60  # in minutes

# Create a new column 'day_of_week' with the day of the week
df['day_of_week'] = df['started_at'].dt.day_name()

df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,ride_duration,day_of_week
0,A847FADBBC638E45,docked_bike,2020-04-26 17:45:00,2020-04-26 18:12:00,Eckhart Park,86,Lincoln Ave & Diversey Pkwy,152.0,41.8964,-87.6610,41.9322,-87.6586,member,27.0,Sunday
1,5405B80E996FF60D,docked_bike,2020-04-17 17:08:00,2020-04-17 17:17:00,Drake Ave & Fullerton Ave,503,Kosciuszko Park,499.0,41.9244,-87.7154,41.9306,-87.7238,member,9.0,Friday
2,5DD24A79A4E006F4,docked_bike,2020-04-01 17:54:00,2020-04-01 18:08:00,McClurg Ct & Erie St,142,Indiana Ave & Roosevelt Rd,255.0,41.8945,-87.6179,41.8679,-87.6230,member,14.0,Wednesday
3,2A59BBDF5CDBA725,docked_bike,2020-04-07 12:50:00,2020-04-07 13:02:00,California Ave & Division St,216,Wood St & Augusta Blvd,657.0,41.9030,-87.6975,41.8992,-87.6722,member,12.0,Tuesday
4,27AD306C119C6158,docked_bike,2020-04-18 10:22:00,2020-04-18 11:15:00,Rush St & Hubbard St,125,Sheridan Rd & Lawrence Ave,323.0,41.8902,-87.6262,41.9695,-87.6547,casual,53.0,Saturday

##### Averge Ride Time

In [32]:
# Calculate average, maximum, and minimum ride times
average_ride_time = df['ride_duration'].mean()
max_ride_time = df['ride_duration'].max()
min_ride_time = df['ride_duration'].min()

print(f"Average Ride Time: {average_ride_time:.2f} minutes")
print(f"Maximum Ride Time: {max_ride_time:.2f} minutes")
print(f"Minimum Ride Time: {min_ride_time:.2f} minutes")

Average Ride Time: 35.59 minutes
Maximum Ride Time: 58720.00 minutes
Minimum Ride Time: -3.00 minutes

In [33]:
# Find the row with the maximum ride duration
max_duration_row = df.loc[df['ride_duration'].idxmax()]

# Find the row with the minimum ride duration
min_duration_row = df.loc[df['ride_duration'].idxmin()]

# Display the results
print("Row with Maximum Ride Duration:")
print(max_duration_row)

print("\nRow with Minimum Ride Duration:")
print(min_duration_row)

Row with Maximum Ride Duration:
ride_id                                     FF4F7C2895AF4127
rideable_type                                    docked_bike
started_at                               2020-04-19 20:50:00
ended_at                                 2020-05-30 15:30:00
start_station_name                    Wabash Ave & Wacker Pl
start_station_id                                         194
end_station_name      HUBBARD ST BIKE CHECKING (LBS-WH-TEST)
end_station_id                                         671.0
start_lat                                            41.8869
start_lng                                            -87.626
end_lat                                                41.89
end_lng                                             -87.6807
member_casual                                         member
ride_duration                                        58720.0
day_of_week                                           Sunday
Name: 17491, dtype: object

Row with Minimum Ride Duration:
ride_id                          3C19503CC3A81CCE
rideable_type                         docked_bike
started_at                    2020-04-29 16:54:00
ended_at                      2020-04-29 16:51:00
start_station_name    Sheffield Ave & Webster Ave
start_station_id                              327
end_station_name        Clark St & Wellington Ave
end_station_id                              156.0
start_lat                                 41.9215
start_lng                                -87.6538
end_lat                                   41.9365
end_lng                                  -87.6475
member_casual                              member
ride_duration                                -3.0
day_of_week                             Wednesday
Name: 25088, dtype: object

In [37]:
negative_durations_count = (df['ride_duration'] < 0).sum()

print(f"Number of rows with negative durations: {negative_durations_count}")

Number of rows with negative durations: 14

The ID with the minimum ride duration seems to be an error since the duration time canot benegative

In [35]:
most_common_day = df['day_of_week'].mode()[0]

print(f"Most Common Day for Starting Rides: {most_common_day}")

Most Common Day for Starting Rides: Sunday